[package]
name = "kisd"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/AsahiLinux/kisd"
license = "MIT"

[dependencies]
bytes = "1.11.1"
clap = { version = "4.6.1", features = ["derive"] }
clap-num = "1.2.0"
env_logger = "0.11.10"
futures-util = { version = "0.3.32", features = ["sink"] }
log = "0.4.29"
nix = { version = "0.31.3", features = ["fs", "term"] }
nusb = { version = "0.2.3", features = ["tokio"] }
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["fs", "io-util", "macros", "net", "rt", "time"] }
tokio-util = { version = "0.7.18", features = ["io"] }
zerocopy = "0.8.48"
zerocopy-derive = "0.8.48"
